services:
  # Development Environment with Claude Code and VS Code Server
  devenv:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: claude-wp-devenv2
    volumes:
      # Mount the host Docker socket to allow Docker in Docker
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount the WordPress code directory
      - ./wordpress:/home/developer/wordpress
      # Mount any SSH keys (optional)
      - ~/.ssh:/home/developer/.ssh:ro
    ports:
      # VS Code Server port
      - "8090:8080"
      # Additional ports for development
      - "3010:3000"
      - "9010:9000"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      # Add any other required environment variables
    restart: unless-stopped
    depends_on:
      - db
      - wordpress
    networks:
      - wp-network

  # WordPress Container
  wordpress:
    image: wordpress:latest
    container_name: claude-wp-wordpress2
    volumes:
      # Mount WordPress content for direct editing
      - ./wordpress:/var/www/html
      # Custom wp-config
      - ./config/wp-config.php:/var/www/html/wp-config.php
      # Custom PHP configuration
      - ./config/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
    ports:
      - "8010:80"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - wp-network
  
  # Database Container
  db:
    image: mysql:8.0
    container_name: claude-wp-db2
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data2:/var/lib/mysql
      - ./config/mysql:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "13316:3306"
    restart: unless-stopped
    networks:
      - wp-network
  
  # PhpMyAdmin (optional)
  phpmyadmin:
    image: arm64v8/phpmyadmin:latest
    container_name: claude-wp-phpmyadmin2
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8091:80"
    depends_on:
      - db
    networks:
      - wp-network

# Persistent Volumes
volumes:
  db_data2:
    name: claude-wp-db-data2

# Docker Networks
networks:
  wp-network:
    name: claude-wp-network2
    driver: bridge
